/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
  experimental: {
    appDir: true,
  },
  publicRuntimeConfig: {
    DIRECTUS_HOST: process.env.DIRECTUS_HOST,
    USER_SERVICE_API_URL: process.env.USER_SERVICE_API_URL,
    USER_SERVICE_URL: process.env.USER_SERVICE_URL,
    GESTION_DE_PROJET_API_URL: process.env.GESTION_DE_PROJET_API_URL,
    INVITE_URL: process.env.INVITE_URL,
    PASSWORD_RESET_URL_ALLOW_LIST: process.env.PASSWORD_RESET_URL_ALLOW_LIST,
    APP_NAME: process.env.APP_NAME,
    ROLE_COLLABORATOR_ID: process.env.ROLE_COLLABORATOR_ID,
    ROLE_CLIENT_ID: process.env.ROLE_CLIENT_ID,
    ROLE_ADMIN_ID: process.env.ROLE_ADMIN_ID,
    COLLABORATORS_EMAILS_DOMAINS: process.env.COLLABORATORS_EMAILS_DOMAINS,
    DIGITAL_SOLUTIONS_TIME_BETWEEN_FACTURES_EMAILS_ALERTS:
      process.env.DIGITAL_SOLUTIONS_TIME_BETWEEN_FACTURES_EMAILS_ALERTS,
    CATALOG_APP_URL: process.env.CATALOG_APP_URL,

    PROJECTS_CHUNK_SIZE: process.env.PROJECTS_CHUNK_SIZE,
    PROJECTS_GLOBAL_CHUNK_SIZE: process.env.PROJECTS_GLOBAL_CHUNK_SIZE,

    AFFAIRS_CHUNK_SIZE: process.env.AFFAIRS_CHUNK_SIZE,
    AFFAIRS_GLOBAL_CHUNK_SIZE: process.env.AFFAIRS_GLOBAL_CHUNK_SIZE,

    FILES_CHUNK_SIZE: process.env.FILES_CHUNK_SIZE,
    FILES_GLOBAL_CHUNK_SIZE: process.env.FILES_GLOBAL_CHUNK_SIZE,

    FACTURES_CHUNK_SIZE: process.env.FACTURES_CHUNK_SIZE,
    FACTURES_GLOBAL_CHUNK_SIZE: process.env.FACTURES_GLOBAL_CHUNK_SIZE,

    SATISFACTION_CHUNK_SIZE: process.env.SATISFACTION_CHUNK_SIZE,
    SATISFACTION_GLOBAL_CHUNK_SIZE: process.env.SATISFACTION_GLOBAL_CHUNK_SIZE,

    CLIENTS_CHUNK_SIZE: process.env.CLIENTS_CHUNK_SIZE,
    CLIENTS_GLOBAL_CHUNK_SIZE: process.env.CLIENTS_GLOBAL_CHUNK_SIZE,

    COLLABORATORS_CHUNK_SIZE: process.env.COLLABORATORS_CHUNK_SIZE,
    COLLABORATORS_GLOBAL_CHUNK_SIZE: process.env.COLLABORATORS_GLOBAL_CHUNK_SIZE,

    CLIENTS_COMPANY_ENTITIES_CHUNK_SIZE: process.env.CLIENTS_COMPANY_ENTITIES_CHUNK_SIZE,
    CLIENTS_COMPANY_ENTITIES_GLOBAL_CHUNK_SIZE: process.env.CLIENTS_COMPANY_ENTITIES_GLOBAL_CHUNK_SIZE,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
};

module.exports = nextConfig;
